name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build backend image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/demo-node-app:latest .

    - name: Push backend image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/demo-node-app:latest

    - name: Build frontend image
      run: |
        cd frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest .

    - name: Push frontend image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup Helm
      uses: azure/setup-helm@v3

    - name: Deploy with Helm
      run: helm upgrade --install my-release ./my-app -n dev
